name: Tests
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.0'
      - name: Install dependencies
        run: |
          make dependencies
      - name: Run vet & lint
        run: |
          make lint
      - name: Run tests
        run: |
          make test
